CREATE TABLE account_tran (
  ID bigint NOT NULL AUTO_INCREMENT,
  ACCOUNT_ID int NOT NULL,
  DATETIME timestamp NOT NULL,
  TRAN_TYPE varchar(10) NOT NULL,
  AMOUNT_REAL decimal(10,2),
  BALANCE_REAL decimal(10,2),
  PLATFORM_TRAN_ID varchar(100),
  GAME_TRAN_ID varchar(100),
  GAME_ID varchar(100),
  AMOUNT_RELEASED_BONUS decimal(10,2) DEFAULT 0,
  AMOUNT_PLAYABLE_BONUS decimal(10,2) DEFAULT 0,
  BALANCE_RELEASED_BONUS decimal(10,2) DEFAULT 0,
  BALANCE_PLAYABLE_BONUS decimal(10,2) DEFAULT 0,
  AMOUNT_FREE_BET decimal(10,2) DEFAULT 0,
  PRIMARY KEY (ID)
);